variable "project" {}
variable "name" {}
variable "location" {}
variable "node-locations" {}
variable "cluster" {}
variable "node-count" {}
variable "node-version" {}
variable "autoscaling-min-node-count" {}
variable "autoscaling-max-node-count" {}
variable "management-auto-repair" {}
variable "management-auto-upgrade" {}
variable "upgrade-max-surge" {}
variable "upgrade-max-unavailable" {}
variable "node-image-type" {}
variable "node-disk-size-gb" {}
variable "node-disk-type" {}
variable "node-machine-type" {}
variable "node-preemptible" {}
variable "node-disable-legacy-endpoints" {}
variable "node-zones" {}