apiVersion: v1
kind: Service
metadata:
  labels:
    app: customer-service
  name: customer-service-service
  namespace: nuvolar
spec:
  clusterIP: 10.92.1.11
  clusterIPs:
  - 10.92.1.11
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8082
    protocol: TCP
    targetPort: 8080
  selector:
    app: customer-service
  sessionAffinity: None
  type: ClusterIP
