apiVersion: v1
kind: Service
metadata:
  labels:
    app: order-service
  name: order-service-service
  namespace: nuvolar
spec:
  clusterIP: 10.92.1.12
  clusterIPs:
  - 10.92.1.12
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8080
  selector:
    app: order-service
  sessionAffinity: None
  type: ClusterIP
